# print('What\'s up, bitch!')
# name = input()
# surname = input()
# print(f'ur name\'s {name} {surname}')
# n = int(input())
# print(14 < n < 16)
# a = int(input())
# b = int(input())
# print(f'{a} * {b} =', a * b)
# print('/\\_/\\')
# print('>^.^<')
# print(' /\\')
# print('(|_|)_/')
# a = int(input())
# prev = int(a - 1)
# theNext = int(a + 1)
# print('The next number for the number %s is %s' %(a, theNext))
# print('The next number for the number %s is %s' %(a, prev))
name = str(input())
age = int(input())
c = 2020 - age
theYear = c + 77

print(f'{theYear}, тебе исполнится 77 лет в {theYear}')